### ISSUE TITLE
Big trouble with first use and display

### ISSUE THREAD

**Issue by rodnem** [exevil/Keys-For-Sketch#4] opened 2017-08-16 14:47 UTC
![image](https://user-images.githubusercontent.com/6350513/29369233-49687ec6-82a2-11e7-827e-a39fb9a45651.png)
Sorry, but I can't use your plugin.
I am running Sketch 462
I have to restart it 3 times before seeing a bad Preferences windows

**Comment by exevil** [comment] 2017-08-16 14:51
@rodnem: Hey! Thanks for the report. Sorry to read. Did this problem come right after you installed the plugin or maybe after an update to the latest version via Sketch update system?

**Comment by rodnem** [comment] 2017-08-16 16:09
I downloaded it and then double-click on it.
I have first update to 462 then install your plug.
After that, when I try it for the first time (click on your tab) Sketch seems to freeze.
I forced the restart. Nothing.
Restart. Nothing.
Then I got the screen you've seen
Kill Craft & Sketch Plugin Monster. Restart
No change :(

**Comment by exevil** [comment] 2017-08-16 16:22
After you forced to restart on freeze did Sketch show you any kind of error sending dialog? If so please try to reproduce this freezing again, restart Sketch and past an error report here.

Without error, I can't even try to find out the reason of this behavior.

**Comment by rodnem** [comment] 2017-08-16 17:05
No, I can't actually get this error sending dialog box.
Interesting test :
I disable all plugins. I Restart Sketch
I enable Keys → it works.
I enable all plugins → it works (slow to display them all)
I close the Preferences dialog.
I reopen it, I select Keys tab and ... 💥 again the destroyed dialog box appears.

So to my mind, there could be a trouble
either with one of my plugin
either with the number of my plugins

**Comment by exevil** [comment] 2017-08-16 17:11
Not sure I can test them all. 🙃 But maybe you can send me a copy of your `Plugins` folder as zip archive (like via Dropbox link or similar)?

**Comment by rodnem** [comment] 2017-08-16 17:25
Sure !
here you can download the zip 
https://drive.google.com/file/d/0B60wzuc_LefzcDJzeDVQbGkyREU/view?usp=sharing

**Comment by exevil** [comment] 2017-08-16 21:36
Even with all the stuff activated I still can't reproduce this bug on my side. 🙄

So the only thing I can do now is waiting for other reports from people with the same issue, sorry. Of course, if you have some time to determine which plugin is causing such a behavior on your machine I'll be really appreciated for your help.

Thanks again for the report.

**Comment by exevil** [comment] 2017-08-17 21:39
Closing for now, will refer to this issue if something similar will appear in future.

Thanks!

**Closed by exevil** 2017-08-17 21:39 UTC
