### ISSUE TITLE
Feature request: backup and restore shortcuts

### ISSUE THREAD

**Issue by RaphyRaph** [exevil/Keys-For-Sketch#2] opened 2017-08-11 14:55 UTC

**Comment by exevil** [comment] 2017-08-11 15:01
Since I'd really like to keep Keys architecture clean and simple to maintain it easily during Sketch updates not sure this feature is the first priority right now. I'll keep this issue opened to let others to support your request.

Thanks again!

**Comment by RaphyRaph** [comment] 2017-08-12 19:08
I guess I should be clearer about why:
1. plugin updates currently override shortcuts
2. fresh installs require resetting shortcuts, which is a huge pain

**Comment by exevil** [comment] 2017-08-13 21:09
Plugin updates shouldn't affect shortcuts that set by Keys because Keys registers this shortcuts on system level. Just like you do when setting a shortcut via the System Preferences. Fresh installs of plugins also shouldn't require any additional actions to apply custom shortcuts afterwards.

Please provide a detailed description of the real flow that can help me to reproduce the things you've mentioned above.

Thanks!

**Comment by RaphyRaph** [comment] 2017-08-14 14:33
Nice, I assumed it set them in the plugin files (like monster keyboard shortcut plugin).

**Comment by exevil** [comment] 2017-08-14 14:37
Ok, then I'm closing the issue for now. Thanks again for your feedback.

**Closed by exevil** 2017-08-14 14:37 UTC

**Comment by highvoltaged** [comment] 2017-10-24 10:18
I think fresh install means, when you reinstall the OS. Since it can take a huge amount of time to remap your keys, i think exporting and importing shortcuts is essential.

I currently make a backup of com.bohemiancoding.sketch.plist it saved my ass 3 times already

**Comment by highvoltaged** [comment] 2017-10-24 10:19
Also i work on multiple computers sometimes, so moving along my shortuts also a must have for me.
